POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Evento Junino !",
    "details": "",    
    "maximumAttendees": 1

}
// faço uma requisição POST
// tenho que informar o tipo do conteudo que estou enviando

###
//f7ef1fef-77b7-4ced-8f25-784047ca4c63
// "events /: eventId / attendees",
POST http://localhost:3333/events/1aeca962-0457-4a61-b80d-dbbd407a1188/attendees
Content-Type: application/json

{
    "name": "Merendinha",
    "email": "merendinhaFazOeli@gmail.com" 
}